### ISSUE TITLE
🐛 Self compiling

### ISSUE THREAD

**Issue by SenpaiHunters** [yeahitsjan/WiredBuddy#1]
Hello 👋 I noticed some small things i might bring up - You stated that:

---

```sh
$ git clone https://github.com/yeahitsjan/WiredBuddy.git
```

Open up ``Wired Buddy.xcodeproj`` in Xcode and hit build!

---

Which is half true, you need to download it using CLI with `git https://github.comyeahitsjan/WiredBuddy.git`, or press the green "Code" button, then press open in Xcode.

Now, to get the app to work, you also need to sign it (or not). So, you would need to explain how to sign the app, and then how to both build and run it. For example:

---

1. Clone this repository using `git clone https://github.com/yeahitsjan/WiredBuddy.git && cd WiredBuddy && open Wired\ Buddy.xcodeproj`. Xcode will open the project.
2. Wait until all dependencies are resolved. This should take a couple of minutes at most.
3. In the file browser on the left, click `WiredBuddy` at the very top. It's the icon with the App Store logo.
4. In the pane that opens on the right, click `Signing & Capabilities` at the top.
5. Under `Signing`, change the `Team` dropdown to `None`.
6. Under `Signing → macOS`, change the `Signing Certificate` to `Sign to Run Locally`.
7. In the Menu Bar, click `Product → Archive` and wait for the build to finish.
8. A new window will open. From the list of WiredBuddy entries, select the topmost one, and click `Distribute App`.
9. In the popup that appears, click `Custom`, then click `Next` in the bottom right of the popup.
10. Click `Copy App`.
11. Open the resulting folder. You'll see an app named WiredBuddy. Drag WiredBuddy to your `/Applications/` folder, and you're all set!

---

Or, in steps 5. you can sign it with your developer ID if you have it. (In step one, the use of `\` is to indicate there is a space for the cli.)

There are only a few bugs I noticed in my quick build and validate, which are"

1. In some cases settings will not appear front and centre
2. Pressing info on "No connection" in the menu bar will shown an alert with a dismiss button, which does not dismiss the alert. 

All in all, good readme 👍 and congrats on the app.

**Comment by yeahitsjan** [comment]
Hi @SenpaiHunters you are absolutely right! Thank you for noticing that. Will update the README as well as the Signing & Capabilities section inside the project to let it sign to run locally.

Also:
1. will check that out, will probably manually bring that view to front
2. I think this is going to be replaced, noticed that too and really annoyed me. Probably will show that in SettingsView under a specific tab "Tips" or smth like that.

Currently at work, but will push changes this afternoon :-)

**Comment by yeahitsjan** [comment]
Both should be fixed right now. Thank you again! Also I linked your comment into the README until I release it as a binary.
