### ISSUE TITLE
v0.1 has incomplete / faulty signing

### ISSUE THREAD

**Issue by dev-yeet** [yeahitsjan/WiredBuddy#3]
Can't right click open like you normally could 

xattr shows it having com.apple.macl but not com.apple.quarantine; not sure how to open in so i'm just going to go back to compiling it in the meantime

![VXhmPqJe-2024-07-02_11 44 32](https://github.com/yeahitsjan/WiredBuddy/assets/3103719/05b33128-c394-4818-a160-503878e84f04)

**Comment by yeahitsjan** [comment]
Hi @dev-yeet! Absolutely normal behavior. I signed with my development ID. Probably need to change that in the future. Here is a guide from Apple to open the application anyway: https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

As stated you can also use "Open Anyway" in settings, your device will remember that. 

> Note: You can also grant an exception for a blocked app by clicking the Open Anyway button in Privacy & Security settings. This button is available for about an hour after you try to open the app.

**Comment by yeahitsjan** [comment]
May I ask if you could check out which of the below versions work out for you?
`NoTeam_SignLocal` has No Team and Sign to Run Locally specified in Xcode
`Team_SignLocal` has my personal team and Sign to Run Locally specified in Xcode

One of those should work with `App Store & verified developers` checked in `Privacy & Security`.
[Build002_NoTeamSignLocal.zip](https://github.com/user-attachments/files/16074868/Build002_NoTeamSignLocal.zip)
[Build002_Team_SignLocal.zip](https://github.com/user-attachments/files/16074869/Build002_Team_SignLocal.zip)

**Comment by yeahitsjan** [comment]
`NoTeamSignLocal` shows me this popup:
<img width="365" alt="grafik" src="https://github.com/yeahitsjan/WiredBuddy/assets/74990847/088e7bc9-3d5b-4312-bea9-9fa405c31c3e">
Which is easily workaround by either Control+Open or the button inside `Privacy & Security`.
`TeamSignLocal` is the same.

I will push a new release with my personal team and SignToRunLocal for now, until feedback.

**Comment by yeahitsjan** [comment]
A good follow up here is:
https://apple.stackexchange.com/questions/388554/is-a-paid-apple-developer-account-required-for-notarizing-macos-apps

I currently do not have a developer account. Notarizing the app will therefore not work.

**Comment by dev-yeet** [comment]
my apologizes, i missed the notifications for the responses. but the new package doens't show the error i was getting. What i mentioned regarding right click open is different, this error specifically said it was malware and i had no way to open it. I didn't feel comfortable trying to override it that point. the new package you uploaded doesn't give that error and i'm able to right click open.

**Comment by yeahitsjan** [comment]
Perfect! Yeah, since Catalina you need an enrolled developer ID to let your app be notarized. The thing why it showed up as malware was due to the signing profile "Development". Your Mac tests against some unique hash-IDs. With development those IDs are just on my device. I got the same error on my MBA, not on my Mini. I am happy that this is fixed, although a warning is showing up still due to being an unverified developer.

**Comment by yeahitsjan** [comment]
Fixed in https://github.com/yeahitsjan/WiredBuddy/commit/088d5bc1bb1105dc6ad0975f653e794923a1dca6 and https://github.com/yeahitsjan/WiredBuddy/releases/tag/0.1-fixsign.
