### ISSUE TITLE
v0.1 moved to bin after opening due to malware detection

### ISSUE THREAD

**Issue by bezibaerchen** [yeahitsjan/WiredBuddy#4]
Downloaded the ZIP. Extracted, moved to Applications.

Upon opening it gets moved to bin right away due to malware detection. Worth mentioning maybe: I am on Sequoia Dev Beta.

Thanks for help

**Comment by yeahitsjan** [comment]
Hi! Same as #3, seems like there is an issue with signing. I'll check that out in the afternoon. Could you meanwhile check the ZIPs attached in #3?

**Comment by bezibaerchen** [comment]
> Hi! Same as #3, seems like there is an issue with signing. I'll check that out in the afternoon. Could you meanwhile check the ZIPs attached in #3?

Giving me this:

![image](https://github.com/yeahitsjan/WiredBuddy/assets/26967080/bca307ab-4a1c-4d6d-be46-a0d3e818f843)

**Comment by bezibaerchen** [comment]
> > Hi! Same as #3, seems like there is an issue with signing. I'll check that out in the afternoon. Could you meanwhile check the ZIPs attached in #3?
> 
> Giving me this:
> 
> ![image](https://private-user-images.githubusercontent.com/26967080/345334170-bca307ab-4a1c-4d6d-be46-a0d3e818f843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTM4NzYsIm5iZiI6MTcxOTk5MzU3NiwicGF0aCI6Ii8yNjk2NzA4MC8zNDUzMzQxNzAtYmNhMzA3YWItNGExYy00ZDZkLWJlNDYtYTBkM2U4MThmODQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3NTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YWI3MDZkZGI4YTU0MWQxNjEwNzZlZmM0OTVlMzBkNTUyNWUyMWE1YWNlNzYzODEzMWVjYzg3NGQwMWY3ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lY7pef3c25P6l2v45ahXQ_FBZZKrH8dy8DZmgYQ1Jlc)

Managed to start it via Settings.

**Comment by yeahitsjan** [comment]
Perfect. I already updated that last night in Xcode settings. I will publish a new release the coming hours, currently not at home. Thank you for testing!

**Comment by yeahitsjan** [comment]
@bezibaerchen can you try https://github.com/yeahitsjan/WiredBuddy/releases/tag/0.1-fixsign and tell me if this fixes your issue? It would make me quite happy :-)

**Comment by bezibaerchen** [comment]
> @bezibaerchen can you try https://github.com/yeahitsjan/WiredBuddy/releases/tag/0.1-fixsign and tell me if this fixes your issue? It would make me quite happy :-)

Same behaviour when simply opening via double-click. Let me know if I should conduct any further tests.

**Comment by yeahitsjan** [comment]
@bezibaerchen you mean the same like the first "contains malware" or "cannot check" and can be opened via settings?

**Comment by bezibaerchen** [comment]
> @bezibaerchen you mean the same like the first "contains malware" or "cannot check" and can be opened via settings?

Exactly. I can release in privacy & security.

**Comment by yeahitsjan** [comment]
@bezibaerchen thats perfect and sadly expected. Since Catalina a dev needs to be enrolled with its developer ID and requires an active subscription. This is something I approach in the future, currently 99$ for such a small open-source app aren't that worth (even though it would be less stressful). I keep it like this for now and set it on the agenda.

Fixed in https://github.com/yeahitsjan/WiredBuddy/commit/088d5bc1bb1105dc6ad0975f653e794923a1dca6 and https://github.com/yeahitsjan/WiredBuddy/releases/tag/0.1-fixsign.
