### ISSUE TITLE
FR : Hide Dock Icon

### ISSUE THREAD

**Issue by Write** [yeahitsjan/WiredBuddy#5]
Title :)

Thanks for this tool.

**Comment by yeahitsjan** [comment]
Hi @Write, thank you! You can already hide the dock icon via the settings. Could you try that out? Third option :-)
![grafik](https://github.com/yeahitsjan/WiredBuddy/assets/74990847/f324f0f6-ac30-4731-a723-7446dfb7b4fb)

**Comment by Write** [comment]
Thanks sorry
